/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author derre
 */
public class mainljframe extends javax.swing.JFrame {

    /**
     * Creates new form mainljframe
     */
    public mainljframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        executar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputcli_nome = new javax.swing.JTextArea();
        digiteseunome_label = new javax.swing.JLabel();
        txtresultado = new javax.swing.JLabel();
        sejarude = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        executar.setText("Executar");
        executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarActionPerformed(evt);
            }
        });
        getContentPane().add(executar);
        executar.setBounds(20, 120, 110, 40);

        inputcli_nome.setColumns(20);
        inputcli_nome.setRows(5);
        jScrollPane1.setViewportView(inputcli_nome);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 190, 40);

        digiteseunome_label.setText("Digite seu nome");
        getContentPane().add(digiteseunome_label);
        digiteseunome_label.setBounds(20, 20, 110, 30);

        txtresultado.setText("Resultado");
        getContentPane().add(txtresultado);
        txtresultado.setBounds(30, 210, 210, 50);

        sejarude.setText("Seja rude");
        getContentPane().add(sejarude);
        sejarude.setBounds(160, 130, 81, 23);

        setBounds(0, 0, 470, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void executarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarActionPerformed
        // TODO add your handling code here:
        if(sejarude.isSelected()){
        txtresultado.setText("Ola idiota, "+ inputcli_nome.getText());
        } else {
        txtresultado.setText("Ola, "+ inputcli_nome.getText());
        }
    }//GEN-LAST:event_executarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainljframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainljframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainljframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainljframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainljframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel digiteseunome_label;
    private javax.swing.JButton executar;
    private javax.swing.JTextArea inputcli_nome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox sejarude;
    private javax.swing.JLabel txtresultado;
    // End of variables declaration//GEN-END:variables
}
