
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vitor
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        abas.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        login_botao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        login_falho = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtsigno = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaocadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        login_botao.setText("Submit");
        login_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_botaoActionPerformed(evt);
            }
        });
        jPanel1.add(login_botao);
        login_botao.setBounds(230, 40, 80, 27);

        jLabel1.setText("Emaill:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 42, 17);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(80, 10, 130, 34);

        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 45, 17);
        jPanel1.add(txtsenha);
        txtsenha.setBounds(80, 60, 130, 30);
        jPanel1.add(login_falho);
        login_falho.setBounds(20, 130, 190, 70);

        abas.addTab("Login", jPanel1);

        jPanel2.setLayout(null);
        jPanel2.add(txtsigno);
        txtsigno.setBounds(150, 20, 310, 34);
        jPanel2.add(txtnome);
        txtnome.setBounds(150, 70, 310, 34);

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        jScrollPane1.setViewportView(txtdesc);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(152, 120, 310, 110);

        jLabel3.setText("Descrição");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 130, 70, 17);

        jLabel4.setText("Signo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 30, 36, 17);

        jLabel5.setText("Nome");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 80, 39, 17);

        botaocadastrar.setText("Submit");
        botaocadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(botaocadastrar);
        botaocadastrar.setBounds(390, 260, 56, 27);

        abas.addTab("Cadastro", jPanel2);

        getContentPane().add(abas);
        abas.setBounds(30, 30, 550, 350);

        setBounds(0, 0, 614, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void login_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_botaoActionPerformed
        // TODO add your handling code here:
        String senha = new String(txtsenha.getPassword());
        if (txtemail.getText().equals("adm") && senha.equals("123")){
            abas.setEnabledAt(1, true);
            abas.setSelectedIndex(1);
        }else{
            JOptionPane.showMessageDialog(null, 
                    "Dados de login incorretos", 
                    "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_login_botaoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void botaocadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocadastrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botaocadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton botaocadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton login_botao;
    private javax.swing.JLabel login_falho;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtsigno;
    // End of variables declaration//GEN-END:variables
}
